#!/usr/bin/zsh

# Example for $XDG_CONFIG_HOME/nsxiv/exec/key-handler
# Called by nsxiv(1) after the external prefix key (C-x by default) is pressed.
# The next key combo is passed as its first argument. Passed via stdin are the
# images to act upon: all marked images, if in thumbnail mode and at least one
# image has been marked, otherwise the current image. nsxiv(1) will block until
# the handler terminates. It then checks which images have been modified and
# reloads them.

# By default nsxiv(1) will send one image per-line to stdin, however when using
# -0 the image list will be NULL separated and the environment variable
# "$NSXIV_USING_NULL" will be set to 1.

# The key combo argument has the following form: "[C-][M-][S-]KEY",
# where C/M/S indicate Ctrl/Meta(Alt)/Shift modifier states and KEY is the X
# keysym as listed in /usr/include/X11/keysymdef.h without the "XK_" prefix.
# If KEY has an uppercase equivalent, S-KEY is resolved into it. For instance,
# K replaces S-k and Scedilla replaces S-scedilla, but S-Delete is sent as-is.

# Multiple files might be passed into the handler. Loop over these
while read file; do
    case "$1" in
	"C-x")
	    # Copy the image path to the clipboard
	    xclip -in -filter | tr '\n' ' ' | xclip -in -selection clipboard ;;
	"p")
	    # Print the selected images to STDOUT
	    echo "$line" ;;
	"r")
	    # Rotate the selected image by 90 degrees. This can last a while for large images, so run it in the background
	    convert -rotate 90 "$file" "$file" ;;
	"R")
	    # Rotate the other way
	    convert -rotate -90 "$file" "$file" ;;
	# TODO: ability to edit RAW files
    esac
done
