#! /bin/bash

# This script searches through all git repositories in $HOME/repo
# and cd's into the selected one.
# It ignores repositories that are in the "stalled" directory.

set -e

cd $HOME/repo
choice=$(/bin/ls \
    | grep -v stalled \
    | sort -u \
    | fzf)
cd - > /dev/null
[[ -n "$choice" ]] \
    && cd "$HOME/repo/$choice" && $SHELL
