#! /bin/bash

# This script searches through all git repositories in $HOME/git
# and cd's into the selected one.
# It ignores repositories that are in the "stalled" directory.

set -e

cd "$HOME/git/renn.es"
choice=$(/bin/ls \
    | sort -u \
    | fzf)
cd - > /dev/null
[[ -n "$choice" ]] \
    && cd "$HOME/git/renn.es/$choice" && $SHELL
