#! /bin/bash

# This script searches through stalled git repositories.
set -e

cd $HOME/git/stalled
choice=$(/bin/ls \
    | sort -u \
    | fzf)
cd - > /dev/null
[[ -n "$choice" ]] \
    && cd "$HOME/git/stalled/$choice" && $SHELL
