#! /bin/bash

# This script is used to sync a local directory with a remote one using unison.
# It notifies you when a conflict occurs and allows you to resolve it manually by running the script again with the -i option.

# Change the following variables to suit your needs:
REMOTE_HOST="cocinero-max" # the remote host to sync with. This MUST be an SSH alias as defined in your ~/.ssh/config file.
REMOTE_DIR="sync"          # the remote directory
LOCAL_DIR="$HOME/.sync"    # the local directory, preferably an absolute path.

# colors, you should not need to change these
YELLOW='\033[1;33m'
ENDCOLOR='\033[0m'

# Verify the remote host is defined in ~/.ssh/config
grep -q "^Host ${REMOTE_HOST}$" ~/.ssh/config || {
    echo "The remote host '${REMOTE_HOST}' is not defined in ~/.ssh/config."
    exit 1
}

# parse arguments
while getopts 'ih' opt; do
    case "$opt" in
      i)
          interactive=1
          ;;
      h)
          echo "Usage: $0 [-i] [-h]"
          echo "  -i: interactive mode: allows you to resolve conflicts manually, only syncs once"
          echo "  -h: this help"
          exit 0
          ;;
  esac
done


# Verify notify-send is installed.
which notify-send &>/dev/null || {
    echo "notify-send is not installed. This script needs it to work."
    exit 1
}

if [[ -n "$interactive" ]]; then
    # interactive mode: sync once with user input and exit
    printf "${YELLOW}Reminder: when faced with a conflict, use '<' and '>' to select which way to force the sync, "
    printf "or just press enter to skip the file and solve the conflict manually later.${ENDCOLOR}\n"
    exec unison -auto -times "${LOCAL_DIR}" "ssh://${REMOTE_HOST}/${REMOTE_DIR}"
fi

counter=0 # count how many times we've failed to sync

while true; do
    unison -auto -batch -times "${LOCAL_DIR}" "ssh://${REMOTE_HOST}/${REMOTE_DIR}"
    # check if unison ran into an error
    [[ $? -eq 0 ]] || {
        counter=$((counter+1))
        # if we've failed 10 times in a row, exit
        [[ $counter -ge 10 ]] && {
            notify-send -t 0 "Unison ran into a conflict or another error" "File sync is stopped, please use '$0 -i' to resolve conflicts manually."
            exit 1
        }
    } && {
        counter=0
    }
    sleep 10
done
