#! /bin/bash

# This script will move a git repo to a "stalled" directory and back.
# It will also remove empty directories so that it doesn't clutter up the directory tree.

set -e
cd $HOME/repo
src=$(fd .git -H -t d \
    | sed 's/\/.git//' \
    | sort -u \
    | fzf)
if [[ -n "$src" ]]; then
    if [[ $src =~ ^stalled/ ]]; then
        # unstall
        dest=${src:8}
    else
        dest="stalled/$src"
    fi
    # make directories if they don't exist
    mkdir -p $(dirname $dest)
    # move the repo
    mv $src $dest
    # remove the directory and all above if empty
    rmdir -p --ignore-fail-on-non-empty $(dirname $src)
fi
cd - > /dev/null
